(TeX-add-style-hook "report"
 (lambda ()
    (LaTeX-add-bibliographies
     "bibliography/bibliography")
    (LaTeX-add-environments
     "nonfloatingfigure"
     "nonfloatingtable")
    (LaTeX-add-labels
     "sec:problem-statement"
     "sec:motivation"
     "chap:evaluation")
    (TeX-add-symbols
     "fref"
     "Fref")
    (TeX-run-style-hooks
     "tikz"
     "ulem"
     "listings"
     "amssymb"
     "stmaryrd"
     "graphicx"
     "subfig"
     "caption"
     "hyperref"
     "fixme"
     "pdflscape"
     "fancyref"
     "babel"
     "british"
     "inputenc"
     "utf8"
     "fontenc"
     "T1"
     "latex2e"
     "memoir10"
     "memoir"
     "a4paper"
     "oneside"
     "final")))

